name: CodeQL

on:
  push:
    branches: [ features/** ]

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          dry_run: true

        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#      - name: "Create release"
#        id: create_release
#        uses: actions/create-release@v1.1.4
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{steps.tag_version.outputs.new_tag}}
#          release_name: Release ${{steps.tag_version.outputs.new_tag}}
#          body: |
#            ${{steps.tag_version.outputs.change_log}}
#          draft: false
#          prerelease: false
        