name: CodeQL

on:
  push:
    branches: [ feature/** ]

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: feature/init
          dry_run: true
        
      - run: |
          docker build -t test/test:0.0.1 .


#      - name: "Create release"
#        id: create_release
#        uses: actions/create-release@v1.1.4
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{steps.tag_version.outputs.new_tag}}
#          release_name: Release ${{steps.tag_version.outputs.new_tag}}
#          body: |
#            ${{steps.tag_version.outputs.change_log}}
#          draft: false
#          prerelease: false
        